"""Add CCF table

Revision ID: 8d0fed19bbcf
Revises: 9081c6d57791
Create Date: 2024-05-07 13:35:03.050643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0fed19bbcf'
down_revision = '9081c6d57791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conferencesCCF',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conferenceId', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('place', sa.String(length=1000), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conferencesCCF')
    # ### end Alembic commands ###
